### ISSUE TITLE
Add environment variable or config file support for logins

### ISSUE THREAD

**Issue by archangelic** [desvox/bbj#10]
I don't like to enter in my username and password every time i launch bbj. Is there any way to have it check for an environment variable for username/password or use a dotfile?

**Comment by desvox** [comment]
Currently it doesn't read passwords or usernanes from the env but that would be easy. I can do that for you. Alternatively you can set your account to a blank password.

**Comment by desvox** [comment]
This took me long enough. Now that im working on BBJ again, this was an easy one.

Theres also been the `--user` launch switch, but now full environment variable support is available. Setting BBJ_USER and BBJ_PASSWORD will work at launch. If the password is wrong, you will be prompted to put it in as normal. The `--user` switch supersedes BBJ_USER. Passwords will never be added as a launch switch. Also `--help` is now a thing.

I've also fixed a bug where the relog option would not work correctly if BBJ was launched with `--user` set.
